merchant/modules/base/controllers/PickupAuditorController.php
<?php

namespace addons\TinyShop\merchant\modules\base\controllers;

use Yii;
use common\helpers\ResultHelper;
use common\enums\StatusEnum;
use common\models\base\SearchModel;
use common\traits\MerchantCurd;
use addons\TinyShop\merchant\controllers\BaseController;
use addons\TinyShop\common\models\pickup\Auditor;

/**
 * 门店自提人员管理
 *
 * Class PickupAuditorController
 * @package addons\TinyShop\merchant\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class PickupAuditorController extends BaseController
{
    use MerchantCurd;

    /**
     * @var Auditor
     */
    public $modelClass = Auditor::class;

    /**
     * 首页
     *
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionIndex()
    {
        $searchModel = new SearchModel([
            'model' => $this->modelClass,
            'scenario' => 'default',
            'partialMatchAttributes' => [], // 模糊查询
            'defaultOrder' => [
                'id' => SORT_DESC,
            ],
            'pageSize' => $this->pageSize,
        ]);

        $dataProvider = $searchModel
            ->search(Yii::$app->request->queryParams);
        $dataProvider->query
            ->andWhere(['>=', 'status', StatusEnum::DISABLED])
            ->andWhere(['merchant_id' => $this->getMerchantId()])
        ->with(['member', 'pickupPoint']);

        return $this->render($this->action->id, [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'pickupPoints' => Yii::$app->tinyShopService->pickupPoint->getMap()
        ]);
    }

    /**
     * 批量删除 - 回收站
     *
     * @param $id
     * @return mixed
     */
    public function actionDeleteAll()
    {
        $ids = Yii::$app->request->post('ids', []);
        if (empty($ids)) {
            return ResultHelper::json(422, '请选择数据进行操作');
        }

        Auditor::deleteAll(['and', ['in', 'id', $ids], ['merchant_id' => $this->getMerchantId()]]);

        return ResultHelper::json(200, '批量操作成功');
    }
}

merchant/modules/base/controllers/PickupPointController.php
<?php

namespace addons\TinyShop\merchant\modules\base\controllers;

use Yii;
use common\enums\StatusEnum;
use common\traits\MerchantCurd;
use common\helpers\ArrayHelper;
use common\models\base\SearchModel;
use addons\TinyShop\common\models\pickup\Point;
use addons\TinyShop\merchant\forms\PickupPointConfigForm;
use addons\TinyShop\merchant\controllers\BaseController;

/**
 * Class PickupPointController
 * @package addons\TinyShop\merchant\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class PickupPointController extends BaseController
{
    use MerchantCurd;

    /**
     * @var Point
     */
    public $modelClass = Point::class;

    /**
     * 首页
     *
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionIndex()
    {
        $searchModel = new SearchModel([
            'model' => $this->modelClass,
            'scenario' => 'default',
            'partialMatchAttributes' => ['name', 'contact', 'mobile'], // 模糊查询
            'defaultOrder' => [
                'sort' => SORT_ASC,
                'id' => SORT_DESC,
            ],
            'pageSize' => $this->pageSize,
        ]);

        $dataProvider = $searchModel
            ->search(Yii::$app->request->queryParams);
        $dataProvider->query
            ->andWhere(['>=', 'status', StatusEnum::DISABLED])
            ->andFilterWhere(['merchant_id' => $this->getMerchantId()]);

        return $this->render($this->action->id, [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * @return mixed|string
     */
    public function actionConfig()
    {
        $request = Yii::$app->request;
        $model = new PickupPointConfigForm();
        $model->attributes = $this->getConfig();
        if ($model->load($request->post()) && $model->validate()) {
            $this->setConfig(ArrayHelper::toArray($model));

            return $this->message('修改成功', $this->redirect(['config']));
        }

        return $this->render('config', [
            'model' => $model,
        ]);
    }
}

merchant/modules/base/views/pickup-point/config.php
<?php

use yii\widgets\ActiveForm;
use common\helpers\Url;
use common\enums\WhetherEnum;

$this->title = '门店自提';
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>

<div class="row">
    <div class="col-sm-12">
        <div class="nav-tabs-custom">
            <?= $this->render('../common/_express_nav', [
                'type' => 'point',
            ]) ?>
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="tab-pane active">
                        <nav class="goods-nav">
                            <ul>
                                <li><a href="<?= Url::to(['pickup-point/index']) ?>">门店管理</a></li>
                                <li class="selected"><a href="<?= Url::to(['pickup-point/config']) ?>">门店运费</a></li>
                                <li><a href="<?= Url::to(['pickup-auditor/index']) ?>">门店审核人员</a></li>
                            </ul>
                        </nav>
                        <div class="box">
                            <?php $form = ActiveForm::begin([
                                'fieldConfig' => [
                                    'template' => "<div class='col-sm-2 text-right'>{label}</div><div class='col-sm-10'>{input}\n{hint}\n{error}</div>",
                                ],
                            ]); ?>
                            <!-- /.box-header -->
                            <div class="box-body table-responsive">
                                <?= $form->field($model, 'pickup_point_fee')->textInput(); ?>
                                <?= $form->field($model, 'pickup_point_freight')->textInput(); ?>
                                <?= $form->field($model,
                                    'pickup_point_is_open')->radioList(WhetherEnum::getMap()); ?>
                                <!-- /.box-body -->
                            </div>
                            <div class="box-footer text-center">
                                <button class="btn btn-primary" type="submit">保存</button>
                                <span class="btn btn-white" onclick="history.go(-1)">返回</span>
                            </div>
                            <?php ActiveForm::end(); ?>
                            <!-- /.box -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

merchant/modules/base/views/pickup-point/edit.php
<?php

use yii\widgets\ActiveForm;
use common\enums\StatusEnum;

$this->title = $model->isNewRecord ? '创建' : '编辑';
$this->params['breadcrumbs'][] = ['label' => '物流配送'];
$this->params['breadcrumbs'][] = ['label' => '门店自提', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">基本信息</h3>
            </div>
            <?php $form = ActiveForm::begin([
                'fieldConfig' => [
                    'template' => "<div class='col-sm-2 text-right'>{label}</div><div class='col-sm-10'>{input}\n{hint}\n{error}</div>",
                ],
            ]); ?>
            <div class="box-body">
                <div class="col-lg-12">
                    <?= $form->field($model, 'name')->textInput(); ?>
                    <?= $form->field($model, 'sort')->textInput(); ?>
                    <?= \common\widgets\provinces\Provinces::widget([
                        'form' => $form,
                        'model' => $model,
                        'provincesName' => 'province_id',// 省字段名
                        'cityName' => 'city_id',// 市字段名
                        'areaName' => 'area_id',// 区字段名
                    ]); ?>
                    <?= $form->field($model, 'address')->textarea(); ?>
                    <?= $form->field($model, 'longitude_latitude')->widget(\common\widgets\selectmap\Map::class, [
                        'type' => 'amap', // amap高德;tencent:腾讯;baidu:百度
                    ]); ?>
                    <?= $form->field($model, 'contact')->textInput(); ?>
                    <?= $form->field($model, 'mobile')->textInput(); ?>
                    <?= $form->field($model, 'status')->radioList(StatusEnum::getMap()); ?>
                </div>
            </div>
            <div class="box-footer text-center">
                <button class="btn btn-primary" type="submit">保存</button>
                <span class="btn btn-white" onclick="history.go(-1)">返回</span>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

merchant/modules/base/views/pickup-point/index.php
<?php

use yii\grid\GridView;
use common\helpers\Url;
use common\helpers\Html;

$this->title = '门店自提';
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>

<div class="row">
    <div class="col-sm-12">
        <div class="nav-tabs-custom">
            <?= $this->render('../common/_express_nav', [
                'type' => 'point',
            ]) ?>
            <div class="tab-content">
                <div class="tab-pane active">
                    <nav class="goods-nav">
                        <ul>
                            <li class="selected"><a href="<?= Url::to(['pickup-point/index']) ?>">门店管理</a></li>
                            <li><a href="<?= Url::to(['pickup-point/config']) ?>">门店运费</a></li>
                            <li><a href="<?= Url::to(['pickup-auditor/index']) ?>">门店审核人员</a></li>
                        </ul>
                    </nav>
                    <div class="box">
                        <div class="box-header">
                            <div class="box-tools">
                                <?= Html::create(['edit']); ?>
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body table-responsive">
                            <?= GridView::widget([
                                'dataProvider' => $dataProvider,
                                'filterModel' => $searchModel,
                                //重新定义分页样式
                                'tableOptions' => [
                                    'class' => 'table table-hover rf-table',
                                    'fixedNumber' => 2,
                                    'fixedRightNumber' => 1,
                                ],
                                'columns' => [
                                    [
                                        'class' => 'yii\grid\SerialColumn',
                                    ],
                                    'name',
                                    'contact',
                                    'mobile',
                                    [
                                        'label' => '地址',
                                        'filter' => false, //不显示搜索框
                                        'format' => 'raw',
                                        'value' => function ($model) {
                                            return $model->address_name . ' ' . $model->address;
                                        },
                                    ],
                                    [
                                        'attribute' => 'sort',
                                        'filter' => false, //不显示搜索框
                                        'value' => function ($model) {
                                            return Html::sort($model->sort);
                                        },
                                        'format' => 'raw',
                                        'headerOptions' => ['class' => 'col-md-1'],
                                    ],
                                    [
                                        'label' => '创建时间',
                                        'attribute' => 'created_at',
                                        'filter' => false, //不显示搜索框
                                        'format' => ['date', 'php:Y-m-d H:i'],
                                    ],
                                    // 'updated_at',
                                    [
                                        'header' => "操作",
                                        'class' => 'yii\grid\ActionColumn',
                                        'template' => '{edit} {status} {delete}',
                                        'buttons' => [
                                            'edit' => function ($url, $model, $key) {
                                                return Html::edit(['edit', 'id' => $model->id]);
                                            },
                                            'status' => function ($url, $model, $key) {
                                                return Html::status($model->status);
                                            },
                                            'delete' => function ($url, $model, $key) {
                                                return Html::delete(['destroy', 'id' => $model->id]);
                                            },
                                        ],
                                    ],
                                ],
                            ]); ?>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>